---
# tasks file for ansible-role-singularity

# Conditionally load in variables for chosen version of Singularity
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ singularity_version }}.yml'
    - ../vars/versions/default.yml
  include_vars: '{{ item }}'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Check that we have valid information about the version we are trying to install
- name: assert version vars
  assert:
    that:
      - "singularity_tarball_checksum not in (None, '')"

- name: Output some debug var stuff
  debug:
    msg:
      - "Singularity version {{ singularity_version }}"
      - "Singularity checksum {{ singularity_tarball_checksum }}"
      - "Singularity filename {{ singularity_tarball_filename }}"

# Install dependencies
- name: Install dependencies needed to build Singularity
  package:
    name:
      "{{ singularity_build_dependencies }}"
    state: present

# Create a version-specific folder for downloading and building Singularity
- name: Create a folder for downloading and building Singularity
  file:
    path: /usr/local/src/singularity-{{ singularity_version }}
    state: directory
    owner: root
    group: root
    mode: '0755'

# Download Singularity
- name: Download Singularity
  get_url:
    url: "https://github.com/hpcng/singularity/releases/download/v{{ singularity_version }}/singularity-{{ singularity_version }}.tar.gz"
    dest: "/usr/local/src/singularity-{{ singularity_version }}/{{ singularity_tarball_filename }}"
    checksum: "sha256:{{ singularity_tarball_checksum }}"

- name: Unpack Singularity
  unarchive:
    remote_src: true
    dest: "/usr/local/src/singularity-{{ singularity_version }}"
    src: "/usr/local/src/singularity-{{ singularity_version }}/{{ singularity_tarball_filename }}"
    creates: "/usr/local/src/singularity-{{ singularity_version }}/singularity"

# Build and install Singularity
- name: Run makeit mconfig
  shell: ". /etc/profile.d/golang.sh ; ./mconfig"
  args:
    chdir: "/usr/local/src/singularity-{{ singularity_version }}/singularity"
    creates: "/usr/local/src/singularity-{{ singularity_version }}/singularity/builddir/Makefile"

- name: Compile Singularity
  command: "make -C ./builddir"
  args:
    chdir: "/usr/local/src/singularity-{{ singularity_version }}/singularity"
    creates: "/usr/local/src/singularity-{{ singularity_version }}/singularity/builddir/singularity"
