---
- name: Converge
  hosts: all
  become: true

  vars:
    - singularity_version: 'v3.6.4'

  pre_tasks:
    - include_tasks: environment-prep.yml

  roles:
    - gantsign.golang
    - zorlin.singularity
